---

- name: Ensure Lago API Worker systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/api-worker/systemd/lago-api-worker.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ lago_identifier }}-api-worker.service"
