# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Lago API Clock systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/api-clock/systemd/lago-api-clock.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ lago_identifier }}-api-clock.service"
    mode: "0644"
