# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure Lago paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ lago_uid }}"
    group: "{{ lago_gid }}"
  with_items:
    - "{{ lago_base_path }}"

- name: Ensure Lago container network is created
  community.general.docker_network:
    name: "{{ lago_container_network }}"
    driver: bridge
