# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Lago path does not exist
  ansible.builtin.file:
    path: "{{ lago_base_path }}"
    state: absent
