# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Lago installation tasks
  tags:
    - setup-all
    - setup-lago
    - install-all
    - install-lago
  block:
    - name: Validate Lago configuration
      when: lago_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Lago base
      when: lago_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/base_install.yml"
    - name: Install Lago API
      when: lago_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/api_install.yml"
    - name: Install Lago API Worker
      when: lago_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/api_worker_install.yml"
    - name: Install Lago API Clock
      when: lago_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/api_clock_install.yml"
    - name: Install Lago Front
      when: lago_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/front_install.yml"
    - name: Install Lago PDF
      when: lago_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/pdf_install.yml"

- name: Perform Lago uninstallation tasks
  tags:
    - setup-all
    - setup-lago
  block:
    - name: Uninstall Lago API Worker
      when: not lago_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/api_worker_uninstall.yml"
    - name: Uninstall Lago API Clock
      when: not lago_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/api_clock_uninstall.yml"
    - name: Uninstall Lago API
      when: not lago_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/api_uninstall.yml"
    - name: Uninstall Lago Front
      when: not lago_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/front_uninstall.yml"
    - name: Uninstall Lago PDF
      when: not lago_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/pdf_uninstall.yml"
    - name: Uninstall Lago base
      when: not lago_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/base_uninstall.yml"
