# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Fail if required Lago settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "lookup('vars', item, default='') | string | length == 0"
  with_items:
    - lago_identifier
    - lago_architecture
    - lago_uid
    - lago_gid
    - lago_hostname
    - lago_path_prefix
    - lago_container_network
    - lago_database_hostname
    - lago_database_password
    - lago_redis_hostname
    - lago_redis_cache_hostname
    - lago_api_environment_variable_lago_rsa_private_key

- name: Fail if Lago architecture is invalid
  ansible.builtin.fail:
    msg: Lago only supports the amd64 and arm64 architectures right now
  when: lago_architecture not in ['amd64', 'arm64']

- name: Run if Traefik is enabled
  when: lago_container_labels_traefik_enabled | bool
  block:
    - name: Fail if Traefik settings required for Lago are not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "lookup('vars', item, default='') | string | length == 0"
      with_items:
        - lago_container_labels_traefik_hostname
        - lago_container_labels_traefik_path_prefix

    - name: Fail if lago_container_labels_traefik_path_prefix is different than /
      ansible.builtin.fail:
        msg: >-
          lago_container_labels_traefik_path_prefix (`{{ lago_container_labels_traefik_path_prefix }}`) must be `/`.
          Lago does not support hosting under a subpath yet.
      when: "lago_container_labels_traefik_path_prefix != '/'"

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `lago_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if lago_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          lago_container_labels_traefik_path_prefix (`{{ lago_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/lago`).
      when: "lago_container_labels_traefik_path_prefix != '/' and lago_container_labels_traefik_path_prefix[-1] == '/'"
