# SPDX-FileCopyrightText: 2026 Suguru Hirahara
# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
    force: true
driver:
  name: docker
platforms:
  - name: lago-${MOLECULE_DISTRO:-ubuntu2604}-default
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2604}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_result_format: yaml
  inventory:
    group_vars:
      all:
        # Helper variables
        lago_debug_service_enabled: false

        # Variables for Lago
        lago_uid: 1000
        lago_gid: 1000
        lago_scheme: http
        lago_hostname: localhost
        lago_container_labels_traefik_enabled: false
        lago_api_container_http_host_bind_port: 3000
        lago_front_container_http_host_bind_port: 80
        lago_architecture: amd64
        lago_api_environment_variable_lago_rsa_private_key: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2UUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktjd2dnU2pBZ0VBQW9JQkFRRFRVeUVkeU5lWFNNQksKRlZ5OUlPVm5Idi83UVNxb1pDRjdzMmFSSG40WkVtRVIyak1FeXJYNFM3Z0szejdITDQrSTV0U1VhcGpUZnNZMwpCK3FjT2JtRkJ0cGlQZ0VEYkpmeTZCd1dIV3BMMkpHMkhubS9lcGNweUhTWW1Vc0E3NnlzWVVWY0hVWDRxSW9rCnFYZnN1Q2F2U09nakJhNWhFUi83SEVlMncyZUhadjJUZ1d4ZHY5TTluOVBFZEMwVzQ1aDVxc2puSy90dzA0TE8KZ1FEUCtlbk5idTdESTRsSjQ2UVpSZCtpUVQ1WmsrNWdpM1U3c0pBUURMeTV4b20zU1hta09CWWZWcWxNSm5YVQppeWVLWHRmVFpZNUZ0c2E2MmY4TlJPTTJKWkVoUGZSUXpFTDAraitaUDRMS1dNWnVjbFQ0Q2lNbnJPTForbUdQCjVhN0hhdnZYQWdNQkFBRUNnZ0VBQWhOMzAxR1U5ZlVEMSt2T3plMkQrTUtLdEQ2eDBHd0V2TnVJZjBET21mNGUKdXdJQVFmbjExZ1hKdmVoRWpITmwveFo1Y2RNbTdqT2tJZDFFNE8rdzZBMThXV2tQaHllVmRKQklMN0FaU21aMQp4QUFYcFJuQXRoWGZPTEtQZnowR05CUCtqa2J4V0RNeEFaR0grVDR6NUd2eHhUVDU2aFUwMGJtTTVpUSs5a3NOCnA3UjNxTmFtUWROV213ZG5YYjJHMXRheTg5ZmJMYlQ4YTYzazVVZVBUWWxXeTNiVUFnV1RTTkhlUklzcFpwWXMKY09KOFF2cUJyR3JZb24rdktVU0o2Y1lsZDA1TkZ0bzM1VGxCR1VVR3RpQjhBM0FMbURtVFVRcWJ0YURWSHZOVApNNzlqWXJhUjhnMkUyTjhmcnpWV3FHSUlnZUE2UWU5SjVvTDFZd254NVFLQmdRRHF6dTgzWGsyTUEzN3RCSVo3Ck04OUw1WkNKRTNNbmt2YmQzS3hRV2NGczFpTWlBYmVXZGZWdzRnNFByRUJJaG1xb0xWV0J0NG4xc3ozdzVPY28KVDhqb3p3N0o5VmZaNkZodjFlMFdHaE1yQmRKWFR1NnViUC9BZVBGWTgzbjZpRW1iaFdMQ1VtZXZNbVBmVENoTwpBVXJLRDg3ODB4azRxV1kwNldJam9NN0pTd0tCZ1FEbVpaL0hxZWJmL1I5V21YMERBcG1hS3VyUkk4a2ZEc1VSClhNd3RUNnRkK3RGM2VuYlQ4SWFobUxUVUdzKytkUWRWU1U3UGV0VXB6TzJvUFhPeDMvZWxsVkhrUmFmNDRVTjgKeGVXMXh6RWJ2blEyQUR3ZTB0ckNGQTdaNDQ1Mml2NDZCRHhSMytPL1o0am9Vdzh1UldJdHBOTTNWT0dMZ2pScAo5bzYzbm0wc0pRS0JnRE1wcytZVW5rRUw0ZlF6TURwWUo2c1o4a3hyK0lOKytsdU5ZZDZBTUMxTzI0amxadU5hCkFJa0FPS0Fob0VBdFNjQXJZSjVMSjd4cHVlMXJjeExOajdGcXJJWkU5MGQ3NFFrOVM5T3RDdEF0REpBSm11aFcKeDhOZ2x2WVMxMWxIcVFKQ0ppckJXZVpLeklnelIvVDNReHlVSlQzaG9YVS9OQTREYkdibSt5ZlJBb0dCQUlEMgpxWFZOdVJudnliYmp1NElQMW9MaE93ZE9ES29Cem5WbGlEUmt2L3VmQmRqbkI5U2ljZm5LVEkzZFpDT3J4aXNMCkdiNHhkMWdxaVd6KzJOL2NDZmI1bWhrNGxFbFBia05OVXNOcGVDZWJkOWt5VUhUQWVncmd4MTlYYk1zV0NpL1gKWnh3OVFuSkZOZkUxYk8zdGtJTVVHOWFCQUs3aWR3eEpJcUhOWURheEFvR0FGZkttR3hFcjN3VzNmdlVxQmlpeApHd3g3RWF0blRIYy9mQ3A0eWhJN1l4ZnFmYmtIVmlCQ1FNQVY3VGZmNms3RU9TVTE4K3NRY0Nhcmx2YTVYaE02Cml4eW1tV0dZb2hhSlNUVmJMMFU1aVBkaDZzN1VxdDZ0Tm53V1hBNnNaSHJaeDB5QnViOUs1aFRrTkFsQi8wYkgKWkRLU1hPUEZjdUg4dWE1YlIyWmpjM0k9Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K"
        lago_api_environment_variable_lago_api_url: http://localhost:3000
        lago_api_environment_variable_lago_front_url: http://localhost:80
        lago_api_environment_variable_secret_key_base: random01d18ea0b43c1673987e194ef4b2d4978e0bf1e6abf83dd32892412b4b62faed17159293a92774017082e1a01c3fb2248af31174b6572a469adeeef730
        lago_api_environment_variable_encryption_primary_key: randomqPAceqj7zDRHgUw1iZHZVGgrH2jkkLIANAI6IYKC7tWa2flM1kfo4OQope
        lago_api_environment_variable_encryption_deterministic_key: randomqPAceqj7zDRHgUw1iZHZVGgrH2jkkLIANAI6IYKC7tWa2flM1kfo4OQope
        lago_api_environment_variable_encryption_key_derivation_salt: randomqPAceqj7zDRHgUw1iZHZVGgrH2jkkLIANAI6IYKC7tWa2flM1kfo4OQope

        # Variables required for Lago to connect to the Postgres database
        lago_database_hostname: "{{ postgres_connection_hostname }}"
        lago_database_port: "{{ postgres_connection_port }}"
        lago_database_username: my_database_username
        lago_database_password: my_database_password
        lago_database_name: lago
        lago_systemd_required_services_list_auto: |
          {{
            (['postgres.service'])
          }}

        # Variables required for Lago to connect to the Valkey data-store
        lago_redis_hostname: "{{ valkey_identifier }}"
        lago_api_container_additional_networks_custom:
          - "{{ valkey_container_network }}"
        lago_api_systemd_required_services_list_custom:
          - "{{ valkey_identifier }}.service"

        # Variables for Postgres
        postgres_uid: 1000
        postgres_gid: 1000
        postgres_connection_password: postgres_password
        postgres_container_network: "{{ lago_container_network }}"
        postgres_managed_databases: |
          {{
            [{
              'name': lago_database_name,
              'username': lago_database_username,
              'password': lago_database_password,
            }]
          }}

        # Variables for Valkey
        valkey_uid: 1000
        valkey_gid: 1000
        valkey_arch: amd64
  env:
    # Workaround for https://github.com/ansible/molecule/issues/4391
    ANSIBLE_ROLES_PATH: ${MOLECULE_PROJECT_DIRECTORY}/..:/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:~/.ansible/roles
scenario:
  # See: https://docs.ansible.com/projects/molecule/configuration/?h=test_sequence#scenario
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # Disable idempotence test for now due to ansible-role-postgres
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
